name: EAS Build

on:
  push:
    branches:
      - main # Adjust branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install EAS CLI
        run: npm install -g eas-cli@3.5.2

      - name: Log in to Expo
        run: |
          echo $EXPO_USERNAME
          expo login --username $EXPO_USERNAME --password $EXPO_PASSCODE
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSCODE }}

      - name: Build Android app
        run: eas build --platform android

      # Add steps to handle artifacts, notifications, etc.
